config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'home/show_resume'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :warning, :danger
  helper_method :current_user, :show_resume

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def show_resume
    pdf_filename = File.join(Rails.root, "public/Resume.pdf")
    send_file(pdf_filename, :filename => "Resume.pdf", :disposition => 'inline', :type => "application/pdf")
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, success: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, success: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<%= javascript_include_tag 'navbar_scroll' %>
<%= stylesheet_link_tag 'home' %>
<script src="http://use.typekit.net/xtk3kmd.js"></script>
<script>
  try {
    Typekit.load();
  } catch (e) {}
</script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Cardo:400,700|Oswald" rel="stylesheet">
<html>
  <body>
    <!-- -->
    <!-- SECTION ONE -->
    <div class="one" id="top">
      <header>
        <!-- Navbar -->
        <nav class="navbar bg-light navbar-expand-lg navbar-light fixed-top scrolling-navbar" id="navbar">
          <div class="collapse navbar-collapse order-1" id="navbarSupportedContent-7">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <p class="intro-nav">
                  <a class="nav-link" href="#top">Home
                    <span class="sr-only">(current)</span></a>
                </p>
              </li>
              <li class="nav-item">
                <p class="intro-nav">
                  <a class="nav-link" href="/Resume.pdf">Resume</a>
                </p>
              </li>
              <li class="nav-item">
                <p class="intro-nav">
                  <a class="nav-link" href="#about-me">About Me</a>
                </p>
              </li>
              <li class="nav-item">
                <p class="intro-nav">
                  <a class="nav-link" href="#projects">Projects</a>
                </p>
              </li>
            </ul>
          </div>
        </header>
        <!-- navbar -->

        <!-- body -->
        <div class=" title-box">
          <!-- Content -->
          <div class="container">
            <div class="col-md-12 mb-4 white-text text-center">
              <h1 class="h1-reponsive white-text text-uppercase font-weight-bold mb-0 pt-md-5 pt-5">
                <strong>Parker Glenn</strong>
              </h1>
              <hr>
              <h2 class="text-uppercase mb-4 white-text sub-title">
                <strong>Computational Linguistics Student</strong>
              </h2>
              <button type="button" class="btn btn-outline-light">
                <a href="#about-me">
                  <p class="intro-nav">About me</p>
                </a>
              </button>
              <button type="button" class="btn btn-outline-light">
                <a href="#projects">
                  <p class="intro-nav">Projects</p>
                </a>
              </button>
              <button type="button" class="btn btn-outline-light">
                <a href="#">
                  <%= link_to "/Resume.pdf", target: :_blank do %>
                  <p class="intro-nav">
                    Resumé
                  </p>
                <% end %>
              </a>
            </button>
            <br><br><br>
            <div align="center" class="media-links">
              <a href="https://www.linkedin.com/in/parker-glenn5/" target="_blank">
                <i class="fa fa-linkedin-square" style="font-size:42px"></i>
              </a>
              <a href="https://github.com/parkervg">
                <i class="fa fa-github" style="font-size:42px" target="_blank"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- -->
    <!-- SECTION TWO -->
    <!-- -->
    <div class="two" id="about-me">
      <div class="info">
        <div class="mask rgba-black-light align-items-center">
          <h2 class="black">
            About me
          </h2>
          <br>
          <p class="black">
            Hi, my name is Parker Glenn and I'm currently a 4th year student at University of California, Santa Barbara. Pursuing a major in Speech and Language Technology, I am fascinated by the intersection of speech and language.
          </p>
        </div>
      </div>

      <div class="card-deck flex-row flex-nowrap">
        <div class="card bg-transparent mb-3 rounded" style="min-width: 20rem; max-height: 30rem;">
          <div class="card-body">
            <h3 class="card-title black">
              Relevant Coursework
            </h3>
            <ul>
              <li class="black">
                LING 120- Corpus Linguistics
              </li>
              <li class="black">
                LING 108- Introduction to Morphology
              </li>
              <li class="black">
                LING 110- Computational Linguistics
              </li>
              <li class="black">
                LING 111- Advanced Computational Linguistics
              </li>
              <li class="black">
                LING 107- Introduction to Phonology
              </li>
              <li class="black">
                LING 106- Introduction to Phonetics
              </li>
            </ul>
          </div>
        </div>
        <div class="card bg-transparent mb-3 rounded" style="min-width: 20rem; max-height: 30rem;">
          <div class="card-body">
            <h3 class="card-title black">
              Skills
            </h3>
            <p class="card-text">
              <ul>
                <li class="black">
                  Python
                </li>
                <li class="black">
                  SQL
                </li>
                <li class="black">
                  NLP Libraries
                </li>
                <li class="black">
                  Machine Learning
                </li>
                <li class="black">
                  Docker
                </li>
                <li class="black">
                  Basic Russian
                </li>
              </ul>
            </p>
          </div>
        </div>
        <div class="card bg-transparent mb-3 rounded" style="min-width: 20rem; max-height: 30rem;">
          <div class="card-body">
            <h3 class="card-title black">
              Future Studies
            </h3>
            <p class="card-text">
              <ul>
                <li class="black">
                  Finish working on personal website.
                </li>
                <li class="black">
                  Continue working on an algorithmic trading bot that integrates sentiment-analysis of companies.
                </li>
                <li class="black">
                  Get to know the underlying concepts of word vectors better.
                </li>
                <li class="black">
                  Finish reading the book "Introduction to Database Systems".
                </li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </div>

    <!-- -->
    <!-- SECTION THREE -->
    <!-- -->
    <div class="three" id="projects">
      <div class="info">
        <div class="mask rgba-black-light align-items-center">
          <h2>
            Projects
          </h2>
          <br>
        </div>
        <div class="table-wrap">
          <table class="table">
            <thead class="thead-light">
              <tr>
                <th>Project Name</th>
                <th>Project Description</th>
                <th>Primary Tools/Concepts</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                  <a href="https://github.com/parkervg/news-article-clustering" target="_blank">
                    <h3>
                      News Article Clustering</h3>
                  </a>
                </td>
                <td class="project-description">
                  <p>
                    A document similarity project I did while in the Data Science club at UCSB.
                    <br><br>
                    With the rise of social media, the ability to publish has been democratized and repetition in the newsfeed runs rampant. This project attempts to group news stories by topic, exploring what specific attributes of text determine topic boundaries.
                    <br><br>
                    Throughout the course of the project, I write a TFIDF algorithm from scratch and manipulate features like entities and publication date in attempts to increase my success rate.
                  </p>
                </td>
                <td>
                  <p>
                    Python, spaCy, Sci-Kit Learn, TFIDF, Seaborn, Matplotlib, SVD, Word Vectors
                  </p>
                </td>
              </tr>

              <tr>
                <td>
                  <a href="https://devpost.com/software/find-a-ride" target="_blank">
                    <h3>
                      Find-A-Ride</h3>
                  </a>
                </td>
                <td class="project-description">
                  <p>
                    A data aggregation tool I built for SB Hacks.
                    <br><br>
                    Finding a carpool to and from a University campus should simple. However, the numerous Facebook rideshare pages, all lacking a normalized data format, makes finding the right ride difficult.
                    <br><br>
                    In Find-A-Ride, I built a Flask API that scrapes the UCSB Rideshare pages and stores the post and post metadata in a BigQuery database. Then, a RandomForest model for classifying intent (Driver vs. Passenger) and a Bidirectional LSTM for extracting
                    entities (e.g. destination, origin, price) are used to convert the unstructured, messy data into structured, query-able data.
                    <br><br>
                    With the data organized, I implement a fuzzy-matching algorithim using features like haversine distance between coordinates and time of day to return a list of rides sorted by relevance matching a user's preferences.
                  </p>
                </td>
                <td>
                  <p>
                    Flask, BigQuery, Selenium, Python, Docker, nginx, gunicorn
                  </p>
                </td>
              </tr>

              <tr>
                <td>
                  <a href="https://github.com/parkervg/troll-tweet-detector/blob/master/Trolliness.ipynb" target="_blank">
                    <h3>
                      Troll Tweet Detector</h3>
                  </a>
                </td>
                <td class="project-description">
                  <p>
                    A school project I completed for LING 111 (Advanced Computational Linguistics).
                    <br><br>
                    In the season surrounding the 2016 U.S. presidential election, the goal of a politial troll was to stir up as much polarization as possible, all while blending in as an average American citizen. One group of online trolls that were notoriously
                    successful were the Russian trolls
                    <br><br>
                    This Jupyter notebook explores concepts both in machine learning and linguistics to create a binomial classifier that identifies a tweet as a troll or non-troll. I rely on certain linguistic quirks of the Russian language, like their lack of articles
                    (e.x. "a", "an", "the") and infrequent use of stopwords.
                  </p>
                </td>
                <td>
                  <p>
                    Python, Scikit-machine learning, Random Forest, feature extraction, spaCy, Jupyter notebook
                  </p>
                </td>
              </tr>

              <tr>
                <td>
                  <a href="https://github.com/parkervg/PersonalWebsite" target="_blank">
                    <h3>
                      Personal Website</h3>
                  </a>
                </td>
                <td class="project-description">
                  <p>
                    The website you're on right now!
                    <br><br>
                    In an attempt to better understand foundational concepts of web development, I tried to create a website to aggregate my work and projects. It is built off Ruby on Rails.
                  </p>
                </td>
                <td>
                  <p>
                    Ruby, Ruby on Rails, Javascript, CSS, HTML
                  </p>
                </td>
              </tr>

            </tbody>
          </table>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParkerWebsite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_login.html.erb
<% if current_user %>
  Logged in as
  <%= current_user.email %>.
  <%= link_to "Log Out", logout_path %>
<% else %>
  <%= link_to "Sign Up", signup_path %>
  or
  <%= link_to "Log In", login_path %>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>